# Generated by Django 2.2.3 on 2019-07-31 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now=True, verbose_name='Date Borrowed')),
                ('due_date', models.DateField(auto_now=True, verbose_name='Due Date')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('camera', 'Camera'), ('light', 'Light'), ('computer', 'Computer'), ('monitor', 'Monitor'), ('audio', 'Audio'), ('misc', 'Miscellaneous')], max_length=10)),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
                ('details', models.CharField(max_length=255, verbose_name='Additional Details')),
                ('serial_num', models.CharField(max_length=50, verbose_name='Serial Number')),
                ('availability', models.BooleanField(default=True, verbose_name='Available?')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(verbose_name='School ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('grad_year', models.IntegerField(verbose_name='Expected Graduation Year')),
                ('current_equipment', models.ManyToManyField(related_name='current_equipment', to='checkouts.Equipment')),
                ('past_equipment', models.ManyToManyField(related_name='past_equipment', to='checkouts.Equipment')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkouts.Student'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='past_checkouts',
            field=models.ManyToManyField(related_name='past_checkouts', to='checkouts.Checkout'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='equipment_to_lend',
            field=models.ManyToManyField(related_name='equipment_to_lend', to='checkouts.Equipment'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkouts.Student'),
        ),
    ]
