# Generated by Django 2.2.3 on 2019-08-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='equipment_to_lend',
            field=models.ManyToManyField(blank=True, related_name='equipment_to_lend', to='checkouts.Equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='past_checkouts',
            field=models.ManyToManyField(blank=True, related_name='past_checkouts', to='checkouts.Checkout'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_equipment',
            field=models.ManyToManyField(blank=True, related_name='current_equipment', to='checkouts.Equipment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='past_equipment',
            field=models.ManyToManyField(blank=True, related_name='past_equipment', to='checkouts.Equipment'),
        ),
    ]
