# Generated by Django 2.2.3 on 2019-08-01 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0005_auto_20190801_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date Borrowed'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='due_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Due Date'),
        ),
    ]
