# Generated by Django 2.2.3 on 2019-08-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0006_auto_20190801_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='equipment_to_lend',
            field=models.ManyToManyField(related_name='equipment_to_lend', to='checkouts.Equipment'),
        ),
    ]
