# Generated by Django 2.2.3 on 2019-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0007_auto_20190801_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='equipment_to_lend',
            field=models.ManyToManyField(blank=True, related_name='equipment_to_lend', to='checkouts.Equipment'),
        ),
    ]
