# Generated by Django 2.2.6 on 2019-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0008_auto_20190802_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
