# Generated by Django 2.2.7 on 2019-11-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0009_checkout_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='equipment_to_lend',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cameras',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'camera'}, related_name='cameras', to='checkouts.Equipment'),
        ),
    ]
