# Generated by Django 2.2.7 on 2019-11-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0010_auto_20191112_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='audio',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'audio'}, related_name='audio', to='checkouts.Equipment'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='computers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'computer'}, related_name='computers', to='checkouts.Equipment'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='lights',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'light'}, related_name='lights', to='checkouts.Equipment'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='misc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'misc'}, related_name='miscellaneous', to='checkouts.Equipment'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='projectors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'projector'}, related_name='projectors', to='checkouts.Equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('camera', 'Camera'), ('light', 'Light'), ('computer', 'Computer'), ('projector', 'Projector'), ('audio', 'Audio'), ('misc', 'Miscellaneous')], max_length=10),
        ),
    ]
