# Generated by Django 2.2.7 on 2020-05-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0013_checkout_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
