# Generated by Django 2.2.7 on 2020-05-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0014_auto_20200505_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Returned'),
        ),
    ]
