# Generated by Django 2.2.7 on 2020-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0015_checkout_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Checkout Notes'),
        ),
    ]
