# Generated by Django 2.2.7 on 2020-05-24 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0016_checkout_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.datetime.today, verbose_name='Request Date')),
                ('due_date', models.DateField(default=datetime.datetime.today, verbose_name='Due Date')),
                ('accepted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('audio', models.ManyToManyField(blank=True, limit_choices_to={'category': 'audio'}, related_name='reservation_audio', to='checkouts.Equipment')),
                ('cameras', models.ManyToManyField(blank=True, limit_choices_to={'category': 'camera'}, related_name='reservation_cameras', to='checkouts.Equipment')),
                ('computers', models.ManyToManyField(blank=True, limit_choices_to={'category': 'computer'}, related_name='reservation_computers', to='checkouts.Equipment')),
                ('lights', models.ManyToManyField(blank=True, limit_choices_to={'category': 'light'}, related_name='reservation_lights', to='checkouts.Equipment')),
                ('misc', models.ManyToManyField(blank=True, limit_choices_to={'category': 'misc'}, related_name='reservation_miscellaneous', to='checkouts.Equipment')),
                ('projectors', models.ManyToManyField(blank=True, limit_choices_to={'category': 'projector'}, related_name='reservation_projectors', to='checkouts.Equipment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkouts.Student')),
            ],
        ),
    ]
