# Generated by Django 2.2.7 on 2020-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0017_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Checkout Notes'),
        ),
    ]
