# Generated by Django 2.2.7 on 2020-06-01 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0018_reservation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='reservation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkouts.Reservation'),
        ),
    ]
